### ISSUE TITLE
Request failed with status code 406

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/nestjs-geteventstore#43]
Hello,
I'm getting the following error, any idea's?

```
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStoreBus] Replace EventBus publisher by Eventstore publish
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStore] Connecting to EventStore
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStoreBus] EventStore connected
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStoreBus] Check if persistent subscription "account" on stream $ce-user needs to be created 
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStoreCore] TcpPackageConnection: connected to [{"host":"127.0.0.1","port":1113}, L{"host":"127.0.0.1","port":59865}, 8d20e00b-1237-42f9-a2cb-7dca66cfa0a0]. +43ms
[Nest] 18667   - 01/12/2021, 7:30:22 PM   [EventStoreCore] TcpConnection: successfully connected to {"host":"127.0.0.1","port":1113} +1ms
Error: Request failed with status code 406
    at createError (/Users/user/Projects/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/user/Projects/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/user/Projects/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:339:22)
    at IncomingMessage.EventEmitter.emit (node:domain:486:12)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
[ERROR] 19:30:22 Error: Request failed with status code 406
```

```
eventstore         | [    1,17,00:31:51.543,INF] Enabling '"$by_category"' projection
eventstore         | [    1,17,00:31:51.554,INF] Enabling '"$stream_by_category"' projection
eventstore         | [    1,17,00:31:51.554,INF] Enabling '"$by_correlation_id"' projection
eventstore         | [    1,17,00:31:51.555,INF] Enabling '"$by_event_type"' projection
eventstore         | [    1,17,00:31:51.555,INF] Enabling '"$streams"' projection
eventstore         | [    1,17,00:31:51.588,INF] '"$by_category"' projection source has been written
eventstore         | [    1,17,00:31:51.593,INF] '"$stream_by_category"' projection source has been written
eventstore         | [    1,17,00:31:51.596,INF] '"$by_correlation_id"' projection source has been written
eventstore         | [    1,17,00:31:51.603,INF] '"$by_event_type"' projection source has been written
eventstore         | [    1,17,00:31:51.610,INF] '"$streams"' projection source has been written
eventstore         | [    1,21,00:34:43.841,INF] External TCP connection accepted: [Normal, "172.22.0.1:55200", L"172.22.0.2:1113", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}].
eventstore         | [    1,28,00:34:43.847,INF] Connection '"external-normal"' ({d8b24e08-7bbc-4bc9-b163-58e58031e85a}) identified by client. Client connection name: '"connection-account-event-handler-and-saga"', Client version: V2.
eventstore         | [    1, 6,00:34:43.898,INF] ES "TcpConnection" closed [00:34:43.898: N"172.22.0.1:55200", L"172.22.0.2:1113", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}]:Received bytes: 104, Sent bytes: 44
eventstore         | [    1, 6,00:34:43.899,INF] ES "TcpConnection" closed [00:34:43.899: N"172.22.0.1:55200", L"172.22.0.2:1113", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}]:Send calls: 2, callbacks: 2
eventstore         | [    1, 6,00:34:43.900,INF] ES "TcpConnection" closed [00:34:43.899: N"172.22.0.1:55200", L"172.22.0.2:1113", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}]:Receive calls: 3, callbacks: 3
eventstore         | [    1, 6,00:34:43.902,INF] ES "TcpConnection" closed [00:34:43.902: N"172.22.0.1:55200", L"172.22.0.2:1113", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}]:Close reason: [Success] "Socket closed"
eventstore         | [    1, 6,00:34:43.903,INF] Connection '"external-normal"":connection-account-event-handler-and-saga"' ["172.22.0.1:55200", {d8b24e08-7bbc-4bc9-b163-58e58031e85a}] closed: Success.
eventstore         | [    1,21,00:34:43.906,DBG] Persistent subscription lost connection from "172.22.0.1:55200"

```

```
EventStoreCqrsModule.registerAsync({
        inject: [ConfigService],
        useFactory: (config: ConfigService) => ({
          credentials: {
            username: config.get('EVENTSTORE_CREDENTIALS_USERNAME'),
            password: config.get('EVENTSTORE_CREDENTIALS_PASSWORD'),
          },
          tcp: {
            host: config.get('EVENTSTORE_TCP_HOST'),
            port: +config.get('EVENTSTORE_TCP_PORT'),
          },
          http: {
            host: config.get('EVENTSTORE_HTTP_HOST'),
            port: +config.get('EVENTSTORE_HTTP_PORT'),
          },
          tcpConnectionName: 'connection-account-event-handler-and-saga',
          options: {
            log: {
              debug: (str, ...args) => {
                Logger.warn(util.format(str, ...args), 'EventStoreCore');
              },
              info: (str, ...args) => {
                Logger.log(util.format(str, ...args), 'EventStoreCore');
              },
              error: (str, ...args) => {
                Logger.log(util.format(str, ...args), 'EventStoreCore');
              },
            },
            // Buffer events if remote is slow or not available
            maxQueueSize: 100_000,
            maxRetries: 10_000,
            operationTimeout: 5_000,
            operationTimeoutCheckPeriod: 1_000,
            // Fail fast on connect
            clientConnectionTimeout: 2_000,
            failOnNoServerResponse: true,
            // Try to reconnect every 10s for 30mn
            maxReconnections: 200,
            reconnectionDelay: 10_000,
            // Production heartbeat
            heartbeatInterval: 10_000,
            heartbeatTimeout: 3_000,
          },
          onTcpDisconnected: () => {
            Logger.error(
              `Connection to eventstore lost`,
              undefined,
              'EventStoreCore',
            );
            //process.exit(137);
          },
          onTcpConnected: () => {
            Logger.error(
              `Connected to eventstore`,
              undefined,
              'EventStoreCore',
            );
          },
        }),
      },
      {
        eventMapper: (data, options: IEventStoreEventOptions) => {
          const className = `${options.eventType}`;
          if (!EventHandlers[className]) {
            return false;
          }
          Logger.debug(
            `Build ${className} received from stream ${options.eventStreamId} with id ${options.eventId}`,
          );
          return new EventHandlers[className](data, options);
        },
        subscriptions: {
          persistent: [
            {
              // Event stream category (before the -)
              stream: '$ce-user',
              group: 'account',
              // autoAck: false,
              bufferSize: 1,
              // Subscription is created with this options
              options: {
                resolveLinkTos: true,
                minCheckPointCount: 1,
              },
            },
          ],
        },
      }),
```

**Comment by Vinceveve** [comment]
Error 406 means the http code that create persistent subscription on $ce-user has an issue. 
Stream does  exists ? If you try to create it from the ui it works ?

**Comment by kodeine** [comment]
@Vinceveve its basically caused by a header[accept] in axios. I manually removed that header and everything works. 

Manually with the ui works as well

if you try to use curl and send request to the ui using accept header, you will see a 406.

**Comment by Vinceveve** [comment]
Did you get the 406 using the lib ? Which version of eventstore are you using ?
We are using in production and never get this issue.
thanks for the feedback

**Comment by kodeine** [comment]
@Vinceveve yes i had to manually go to node_modules/axios and remove the header['Accept'] and then it works.

i'm using eventstore using docker config below.

```
eventstore:
    container_name: eventstore
    hostname: eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"
```

**Comment by Vinceveve** [comment]
Ok found it `image: eventstore/eventstore:latest` you should use `image: eventstore/eventstore:5.0.8`.

On EventStore latest (20.6) they have switched to GRPC and nothing works exactly the same.
I'm waiting for the official driver to rollout to release a 2.0.0 (https://github.com/EventStore/EventStore-Client-NodeJS)  0.0.0-alpha13 does not looks stable enough 👯

**Comment by kodeine** [comment]
@Vinceveve i am trying to use eventstore cloud and it seems like they only support 20* version. 

https://github.com/EventStore/EventStore-Client-NodeJS states, "This client is compatible with version 20.6.1 upwards." is it possible yet to upgrade this lib?

Also, how are you using the eventstore db on production? can you share the setup for production use?

Thank you
