### ISSUE TITLE
Cannot set property 'isConnected' of undefined

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/nestjs-geteventstore#53]
```
[EventStoreCore] TypeError: Cannot set property 'isConnected' of undefined
    at EventStoreStreamCatchUpSubscription._subscriptionDropped (/Users/user/Projects/abc/node_modules/nestjs-geteventstore/dist/event-store.class.js:154:67)
    at EventStoreStreamCatchUpSubscription.module.exports.EventStoreCatchUpSubscription._dropSubscription (/Users/user/Projects/abc/node_modules/node-eventstore-client/lib/dist.js:5945:12)
    at /Users/user/Projects/abc/node_modules/node-eventstore-client/lib/dist.js:5838:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9) Catch-up Subscription to %s: subscriptionDropped callback failed. $ce-report +3ms
```

**Comment by jdharandas** [comment]
Do you still have this error ? What version of the lib are you using ?

**Comment by kodeine** [comment]
I guess you can close this for now, since this repo has been updated a lot now. i got this error on `1.6.4`.
