### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by riseno** [PrestaShopCorp/nestjs-geteventstore#67]
Am i missing something?

```
/Users/ryanchan/repositories/nestjs/cqrs-app/node_modules/nestjs-geteventstore/dist/cloudevents/write-events-prepublish.service.js:45
            const version = event?.metadata?.version ?? defaultVersion;
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ryanchan/repositories/nestjs/cqrs-app/node_modules/nestjs-geteventstore/dist/cloudevents/index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by AlexandreDecollas** [comment]
I fixed the issue by upgrading node to version 14.17.3
